name: app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 < 4.0.0"

dependencies:
  animate_do: ^3.3.4
  badges: ^3.1.2
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.4.1
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  dots_indicator: ^3.0.0
  file_picker: ^8.1.2
  firebase_core: ^3.4.1
  flutter:
    sdk: flutter
  flutter_iconly: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.8
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: any
  intl_utils: ^2.8.7
  provider: ^6.1.2
  razorpay_flutter: ^1.3.7
  shared_preferences: ^2.3.2
  syncfusion_flutter_charts: ^26.2.14
  syncfusion_flutter_gauges: ^26.2.13
  syncfusion_flutter_sliders: ^26.2.14

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section like this:
  assets:
    - assets/
    - assets/onboarding.png
    - assets/1.png
    - assets/2.png
    - assets/file.svg
    - assets/locale/intl_en.arb
    - assets/locale/intl_hi.arb
    - assets/locale/intl_te.arb